<?php

// function bridge_page_attachments_alter(array &$page) {
//     $path = $current_path = \Drupal::service('path.current')->getPath();
//     if ($path == '/node') {
//         $page['#attached']['library'][] = "bridge/bridge";
//     }
// }

function bridge_preprocess_page(&$variables) {
    if ($variables['is_front'] == TRUE) {
        $variables['#attached']['library'][] = 'bridge/home';
    }
}